### ISSUE TITLE
Fun Fair Maze should have three states per tile

### ISSUE THREAD

**Issue by Michael1337** [SchulESB/pokeheroes#1]
Hey,

the fun fair maze should have three states for each way: [unpassable, passable, passed]
So when you see that you can only move up and right from a position, you can mark those two as passable. If you decide to go right, you mark it as passed. This way, you can back track to uncharted places more easily later.

Technically, instead of doing it with checkboxes, you can probably do it with data-items.

```html
<label class="container all-blocks">
  <span class="block-color-2 left" data-state="0"></span>
</label>
<label class="container all-blocks">
  <span class="block-color-2 right" data-state="0"></span>
</label>
<label class="container all-blocks">
  <span class="block-color-2 down" data-state="0"></span>
</label>
```

```css
.block-color-2[data-state="0"] { background: #888; }  /* Unpassable */
.block-color-2[data-state="1"] { background: #ff0; }  /* Passable */
.block-color-2[data-state="2"] { background: #0f0; }  /* Passed */
```

```javascript 
document.addEventListener("DOMContentLoaded", function() {
  document.querySelectorAll('.block-color-2').forEach(span => {
    span.addEventListener('click', function() {
      let state = parseInt(this.dataset.state, 10);
      state = (state + 1) % 3;
      this.dataset.state = state;
    });
  });
});
```
